services:
  - type: web
    name: crypto-dashboard-api
    env: python
    buildCommand: docker build -t your-image-name .
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
